### ISSUE TITLE
Refactor CI Pipeline to Use `uv` for Dependency Installation

### ISSUE THREAD

**Issue by robbiemu** [robbiemu/clarifAI#90]
Our current CI workflow in `.github/workflows/ci.yml` manually lists all project dependencies for installation using `pip`. This approach was a pragmatic short-term fix but has several long-term maintainability issues:

1.  **Violation of DRY Principle:** The list of dependencies is duplicated between our `pyproject.toml` files and the `ci.yml` file.
2.  **Maintenance Overhead:** Whenever a dependency is added or changed in any service, a developer must remember to also update the `ci.yml` file, which is error-prone.
3.  **Inconsistency with Local Development:** We use `uv` and its workspace features for local development, but the CI pipeline uses `pip`. This discrepancy can lead to "it works on my machine" issues and makes the CI environment a less accurate reflection of the local setup.

The root cause of this is that standard `pip` does not understand the `[tool.uv.workspace]` configuration in our root `pyproject.toml`, and therefore cannot discover and install the packages from our `services/` and `shared/` directories automatically.

### Proposed Solution

To resolve this, we should refactor the CI pipeline to use `uv` for dependency management, making it consistent with our local development workflow. This will make `pyproject.toml` the single source of truth for all dependencies.

The implementation should involve the following steps in the `test` job of our `ci.yml`:

1.  **Install `uv`:** Add a step to install `uv` itself into the runner's environment.
    ```yaml
    - name: Install uv
      run: pip install uv
    ```
2.  **Create and Cache a Virtual Environment:** Use `uv venv` to create a virtual environment. This is a best practice for isolation and enables highly effective caching with `actions/cache`. The cache key should be based on the hash of our `uv.lock` file, so the environment is only rebuilt when dependencies change.
    ```yaml
    - name: Cache Python virtual environment
      uses: actions/cache@v4
      id: cache-venv
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/uv.lock') }}
        restore-keys: |
          ${{ runner.os }}-python-${{ matrix.python-version }}-
    ```
3.  **Install Dependencies with `uv`:** Replace the manual `pip install` list with a single `uv pip install` command. This command will correctly read the workspace configuration from `pyproject.toml` and install all packages and their dependencies. This step should only run if the cache was not restored.
    ```yaml
    - name: Install dependencies
      if: steps.cache-venv.outputs.cache-hit != 'true'
      run: |
        uv venv
        uv pip install -e ".[dev]"
    ```
4.  **Update Subsequent Steps:** All subsequent steps that run Python commands (e.g., `pytest`, `ruff`, `bandit`) must be updated to first activate the virtual environment.
    ```yaml
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest
    ```

### Acceptance Criteria

-   The manual list of dependencies in `ci.yml` is removed.
-   The CI pipeline uses `uv` to install all project dependencies from `pyproject.toml`.
-   A virtual environment is created and cached to speed up subsequent CI runs.
-   All CI jobs (linting, testing, security scans) continue to pass successfully using the new `uv`-managed environment.
-   The CI configuration is cleaner, more maintainable, and more consistent with the local development setup.
